name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Build
        run: |
          pnpm i
          pnpm run build

      - name: Get version info
        id: version
        run: |
          echo "name=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - name: Package plugin archive
        run: |
          mkdir ${{ github.event.repository.name }}
          cp main.js styles.css manifest.json README.md ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}-${{ steps.version.outputs.name }}.zip ${{ github.event.repository.name }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ${{ github.event.repository.name }}-${{ steps.version.outputs.name }}.zip
            styles.css
            main.js
            manifest.json
          name: ${{ steps.version.outputs.name }}
          prerelease: false
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
